/* =========================================================
   VSTEP WRITING SYSTEM - SUPABASE AUTH INTEGRATION SCHEMA
   Proper Supabase Auth + RLS Integration
   ========================================================= */

-- =============================
-- 0. EXTENSIONS
-- =============================
create extension if not exists "uuid-ossp";

-- =============================
-- 1. LOOKUP TABLES (Same as before)
-- =============================
create table if not exists levels (
  level_id integer generated by default as identity primary key,
  level_code varchar(5) unique not null,
  description varchar(100)
);

create table if not exists part_types (
  part_type_id integer generated by default as identity primary key,
  code varchar(20) unique not null,
  description varchar(100)
);

create table if not exists practice_modes (
  mode_id integer generated by default as identity primary key,
  code varchar(30) unique not null,
  description varchar(100)
);

create table if not exists hint_types (
  hint_type_id integer generated by default as identity primary key,
  code varchar(30) unique not null,
  description varchar(100)
);

create table if not exists prompt_purposes (
  purpose_id integer generated by default as identity primary key,
  code varchar(30) unique not null,
  description varchar(100)
);

create table if not exists sample_types (
  sample_type_id integer generated by default as identity primary key,
  code varchar(20) unique not null,
  description varchar(100)
);

-- =============================
-- 2. USER PROFILE (Supabase Auth Integration)
-- =============================
-- This table references Supabase Auth users
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name varchar(100) not null,
  username varchar(100) unique not null,
  email varchar(150) unique not null,
  phone_number varchar(20),
  role varchar(20) default 'User',
  target_level_id integer references levels(level_id),
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz
);

-- =============================
-- 3. TRIGGER FUNCTION - Auto-create profile on user signup
-- =============================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, name)
  values (new.id, new.email, new.email, new.email); -- Use email as default username/name
  return new;
end;
$$ language plpgsql security definer;

-- =============================
-- 4. TRIGGER - Execute on new auth user
-- =============================
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =============================
-- 5. EXAM STRUCTURE (Same structure)
-- =============================
create table if not exists exam_structures (
  exam_structure_id integer generated by default as identity primary key,
  name varchar(100) not null,
  description text,
  total_parts integer not null,
  duration_minutes integer,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists parts (
  part_id integer generated by default as identity primary key,
  exam_structure_id integer references exam_structures on delete cascade,
  part_type_id integer references part_types,
  part_number integer not null,
  title varchar(200),
  instructions text,
  time_limit integer,
  min_words integer,
  max_words integer
);

-- =============================
-- 6. PRACTICE SESSIONS
-- =============================
create table if not exists practice_sessions (
  session_id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  mode_id integer references practice_modes,
  is_random boolean default true,
  status varchar(20) default 'active',
  started_at timestamptz default now(),
  ended_at timestamptz
);

-- =============================
-- 7. TOPICS & CONTENT
-- =============================
create table if not exists topics (
  topic_id bigint generated by default as identity primary key,
  part_id integer references parts on delete cascade,
  difficulty_level_id integer references levels,
  topic_name varchar(255) not null,
  content text,
  context text,
  purpose text,
  recipient_role varchar(100),
  min_words integer,
  max_words integer,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- =============================
-- 8. USER SUBMISSIONS
-- =============================
create table if not exists user_submissions (
  submission_id bigint generated by default as identity primary key,
  session_id bigint references practice_sessions on delete cascade,
  topic_id bigint references topics,
  part_id integer references parts,
  content text not null,
  word_count integer,
  submitted_at timestamptz default now()
);

-- =============================
-- 9. AI EVALUATION
-- =============================
create table if not exists ai_evaluations (
  evaluation_id bigint generated by default as identity primary key,
  submission_id bigint unique references user_submissions on delete cascade,
  total_score float,
  estimated_level_id integer references levels,
  overall_feedback text,
  strengths text,
  weaknesses text,
  suggestions text,
  evaluated_at timestamptz default now()
);

-- =============================
-- 10. PASSWORD RESET TOKENS
-- =============================
create table if not exists password_reset_tokens (
  token_id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  token varchar(100) unique not null,
  expires_at timestamptz not null,
  used boolean default false,
  created_at timestamptz default now()
);

-- =============================
-- 11. SEED DATA
-- =============================
insert into levels (level_code, description) values
('A1','Beginner'),
('A2','Elementary'),
('B1','Intermediate'),
('B2','Upper Intermediate'),
('C1','Advanced'),
('C2','Proficient')
on conflict (level_code) do nothing;

insert into part_types (code, description) values
('writing_part1','Email / Letter'),
('writing_part2','Essay')
on conflict (code) do nothing;

insert into practice_modes (code, description) values
('full_test','Full Test'),
('by_part','Practice by Part'),
('timed','Timed Practice'),
('untimed','Untimed Practice'),
('random','Random Topics')
on conflict (code) do nothing;

-- =============================
-- 12. ROW LEVEL SECURITY
-- =============================
alter table profiles enable row level security;
alter table practice_sessions enable row level security;
alter table user_submissions enable row level security;
alter table password_reset_tokens enable row level security;

-- =============================
-- 13. RLS POLICIES
-- =============================

-- Profile: user can access own profile
create policy "Profile self access"
on profiles
for all
using (id = auth.uid());

-- Sessions: user manages own sessions
create policy "Session self access"
on practice_sessions
for all
using (user_id = auth.uid());

-- Submissions: user manages own submissions
create policy "Submission self access"
on user_submissions
for all
using (
  session_id in (
    select ps.session_id
    from practice_sessions ps
    where ps.user_id = auth.uid()
  )
);

-- Password reset tokens: user can access own tokens
create policy "Password reset token self access"
on password_reset_tokens
for all
using (user_id = auth.uid());

-- =============================
-- 14. INDEXES
-- =============================
create index if not exists idx_profiles_username on profiles(username);
create index if not exists idx_profiles_email on profiles(email);
create index if not exists idx_sessions_user on practice_sessions(user_id);
create index if not exists idx_submissions_session on user_submissions(session_id);

-- =============================
-- VERIFICATION
-- =============================
select 'Supabase Auth integration schema created successfully' as status;
select count(*) as levels_count from levels;
select count(*) as part_types_count from part_types;
select count(*) as practice_modes_count from practice_modes;