// <auto-generated />
using Infrastructure.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301190000_AddUserProfilesTable")]
    partial class AddUserProfilesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model unchanged; this migration only adds user_profiles table.
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
