# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

[project]
name = "vstep-writing-system"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_enable_signup = true
email_double_confirm_changes = false
email_confirm_timeout = 300
flow_type = "pkce"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54324
vector_port = 54325